### ISSUE TITLE
Resource Page

### ISSUE THREAD

**Issue by UncommonUnion** [UncommonUnion/WCV#10]
"There is a need for a clearer and more structured way of browsing through resources. For now the page has only a search function which does not produce great results. The resources need to be listed, structured or categorized in some visible way.  We have also requested that the handbooks be featured in the different languages as they are the key resources at present."

**Comment by UncommonUnion** [comment]
Search works against categories, so you can refine results based on how content is set up in the system. We can add a handbook content; is the idea to present the handbooks as an index (prior to search) or just return in search results? Currently it results return thumbnail, title, excerpt, and categories. This was the structure approved in the planning documents (accessible from the client area.) Initially there was an index page (prior to search results) we were told to remove.

**Comment by UncommonUnion** [comment]
"We would be keen to review additional design mock-ups for this page. Search function should be secondary to a clear, visible listing of resources."

**Comment by lamminmaki** [comment]
The handbooks can be presented as PDFs (like in http://www.constitutionmakingforpeace.org/?q=resource-center). 

The handbook PDFs should also be highlighted as the "Featured Resources" - nothing else needs to be featured at this point. 

Instead of the WCV logo, can each Handbook PDF have the thumbnail of the actual handbook (like here: http://www.constitutionmakingforpeace.org/?q=resource-center).

**Comment by lamminmaki** [comment]
The search function should not produce individual sections and sub-sections of the handbook as results - only the six different PDF versions. We will test the search function at a later stage once we can add more resources. 

Thank you for the mock-up http://uncommonunion.com/client-work/wcv/design/revisions/index.php?page=resources. We will still look into this. Would it be possible for us to add a similar index later on, using the available templates?

**Comment by lamminmaki** [comment]
I also wanted to have a final confirmation on the database question. We already discussed earlier that WCV and CMP share the same database. This should ensure that the WCV search function produces results from the CMP site. Can you confirm if this is indeed the case?

**Comment by UncommonUnion** [comment]
We've set up the resource page with the 6 PDF handbooks as in your link. Yes, CMP and WCV shares the same database.

Unfortunately Wordpress cannot search against PDFs, only the database... so it will return records the same way your current CMP site does, for example:

http://www.constitutionmakingforpeace.org/?q=search/node/box

**Comment by lamminmaki** [comment]
We notice you have added a "Handbook" section to the "Resources" page (http://dev-constitution-making-for-peace.pantheonsite.io/womens-constitution-making-voices/resources/). This is similar to what was on the site before and it is not exactly what we are looking for. 

We would need a "Featured Resources" section, which highlights the handbooks - but also other resources that are considered important.  This section should - at this point - include the six different handbook PDFs with their thumbnails. But we should have the ability to add new featured resources as they become available. The "Featured resources" section can be visible both on the "Home" page and the "Resources" page. 

I've tried to sketch out the layout of the "Resources" page, including how the "Featured resources" section should look like. On "Home" page, the "Featured resources" section is in a smaller column so on that page the layout could be different. 

Please let me know if this is unclear or if you have any questions. 

![featured resources](https://cloud.githubusercontent.com/assets/19553399/17692516/56cd8278-639a-11e6-9c03-fded71109f1b.png)

**Comment by lamminmaki** [comment]
I was trying to work on a solution to the "Featured resources" problem (presenting handbooks with other resources as well) and thought about doing this in the post format. The problem is, the handbook thumbnail is not fully visible (see attached picture). Look forward to any solutions you might have. 

![featured resource thumbnail](https://cloud.githubusercontent.com/assets/19553399/17704024/f2852458-63d3-11e6-8238-193bd5b4525f.png)

**Comment by lamminmaki** [comment]
Update to my last comment: I tried with a smaller image and now it looks perfect. However, once I open the post the featured image looks quite small. Is there a way to disable the featured image from the post itself and use a larger file instead? 

![handbook icon too small](https://cloud.githubusercontent.com/assets/19553399/17704403/43d9bfe8-63d5-11e6-90e2-adf4d4a354ac.png)

**Comment by UncommonUnion** [comment]
done

**Comment by lamminmaki** [comment]
Thanks Paul - we're moving in the right direction. However, I would have hoped this to look a bit more appealing visually. My paint drawing was merely a sketch of the overall layout without much thought for visual details. 

I would suggest we have 6 items in total in two rows, so 3 and 3. This would give us more space to give a bit more info about the resources (see attached image for an idea). This could include title, publication date, thumbnail, as in the example. 

 It would be good to add pagination in case there are more than 6 resources. Lines or boxes separating the resources from each other might also make the page more appealing.

![resources](https://cloud.githubusercontent.com/assets/19553399/18055755/71ec5470-6e09-11e6-8fde-9d74b95552fc.png)

**Comment by lamminmaki** [comment]
Please also note that this page is still called "Resources". "Featured resources" is the first sub-section. Sorry if that was unclear.

**Comment by UncommonUnion** [comment]
done

**Comment by lamminmaki** [comment]
OK!
