### ISSUE TITLE
Voice Box Size

### ISSUE THREAD

**Issue by UncommonUnion** [UncommonUnion/WCV#17]
Voices page: The boxes on this page need to be the same size. They should also be a bit smaller so that at least four can fit on the screen without being cut.

**Comment by UncommonUnion** [comment]
I reduced the descriptions from 3 lines to 2 lines. Set maximum title size to 2 lines. Reduced maximum image size. The boxes are now smaller and same height.

NOTE: Screen resolutions vary considerably. There is no way of making sure 4 boxes will be visible on all screens.

**Comment by lamminmaki** [comment]
OK!
