### ISSUE TITLE
About Page Accordion

### ISSUE THREAD

**Issue by UncommonUnion** [UncommonUnion/WCV#18]
About page: Make the Constitution-making for Peace text always visible, and not only through clicking the logo, which is something that a visitor won’t necessarily do. The section with logos should not be called “Interpeace” but “Partners” or “Co-organizers”.

**Comment by UncommonUnion** [comment]
done.

**Comment by lamminmaki** [comment]
How can we edit the content of the sidebar in "About" page? For instance, if we want to add a new partner.

**Comment by UncommonUnion** [comment]
This needs to be edited in the template. This is potentially complex to exposed to the editor because it includes images, links, variety of styles, ordering, default open state (which item is active on load),etc. To parameterize all of the that is doable, but if you are only going to change this occasionally (if at all) it is not really worth it...

**Comment by UncommonUnion** [comment]
Also, the HTML of the side bar CAN be edited in the theme editor (within wordpress) which gives you access to the files. The file you need to edit is called "sidebar-cv-about.php" in the "Constitution Making For Peace" theme. This is the link:

https://dev-constitution-making-for-peace.pantheonsite.io/wp-admin/theme-editor.php?file=sidebar-wcv-about.php&theme=cmp

**Comment by lamminmaki** [comment]
OK - noted!
