### ISSUE TITLE
Hide Tweets on Homepage

### ISSUE THREAD

**Issue by UncommonUnion** [UncommonUnion/WCV#19]
Homepage:  Hide “Tweets” section for now. Are videos hosted on the homepage are in different formats (Vimeo, YouTube) is there a way to make them uniform – how should we format the videos we are creating to best fit with your build.

**Comment by UncommonUnion** [comment]
Generally speaking, a standard 16:9 aspect ratio is the best for YouTube and Vimeo. The sites themselves will handle the transcoding.

**Comment by UncommonUnion** [comment]
OK.

Please add “Featured Resources” on home page – below “Featured Voices”. 

Hide “Tweets” section. Refine layout accordingly.

**Comment by UncommonUnion** [comment]
Done.

**Comment by lamminmaki** [comment]
OK!
