### ISSUE TITLE
Network Privacy

### ISSUE THREAD

**Issue by UncommonUnion** [UncommonUnion/WCV#20]
The site should have two networks, one that is available for everyone through the registration form. The second one is a closed practitioner network that can be accessed by invitation or permission function only. We would need clarifications in this regard.

Ideally, we would invite everyone to join the regular network after which invitations or permissions would be sent to chosen individuals to join the closed network. However, it remains unclear how this has been implemented in practice. The dummy account reveals the “Expert Network” in the top menu. Yet, there are no options for creating groups, sharing resources etc. once you are on the expert network page. It is also unclear how users will get access to the closed network. 

Provide further information as to how the closed network functions, ensures security of users, and is separate from the public network. 

Please place “Expert Network” under Network heading as a dropdown option once logged in.

**Comment by UncommonUnion** [comment]
Ok. This is how the privacy works. (This is based on feedback to date and some adjustments made based on comments above.)

There are 3 kinds of groups: public, private, and hidden.

Any registered member can create / see a public group. Expert-status user can create / see private and hidden groups. Private groups are accessible on a page only visible to expert users which is under "Expert Network" in the navigation.

Hidden groups, however, can only be seen from a user's profile page.

Within each group there is a document page page. Users can upload resources here to share with the membership of their group.

Expert user (with access to private / hidden) groups can only be granted by the administrator.

If you wish to review this:

Expert User:
Millie
abc123

Public User:
Roya
abc123

**Comment by UncommonUnion** [comment]
Also, individual members can control whether their activity is public, private, etc. Default is that activity is only shared with friends. Also, the profile of members can be hidden as well.

**Comment by lamminmaki** [comment]
Thanks for the clarifications Paul - we still need to do a bit more testing to see how everything works and if this solution works for us. 

I would say the main concern we have is over the separation of the two networks. For instance, is it possible for a member to remain anonymous (apart from other expert users perhaps)? Can the profile be hidden already when signing up? 

Creating groups is another concern, as groups created through the Expert Network can actually end up in the Open Network, if a user does not choose the correct option. Are there any solutions to make them truly separate, and safer for those who wish to remain anonymous?

**Comment by UncommonUnion** [comment]
The only way you can make them _truly_ separate would be to have 2 wordpress installations and put  one behind a firewall I suppose - which would introduce many other issues... You will likely want to search both, for example, in a single query. If you have a unique requirement for your network that might require custom development on top of the privacy controls we may need to build something from scratch to extend Buddypress... if this is the case, we will need to clarify the details of such requirements because this would be outside the current scope. That being said Buddypress is very robust... so yes, it is possible to hide profiles as I mentioned, but if there are details regarding how / when exactly that must be done, custom development might be needed.

**Comment by lamminmaki** [comment]
OK - we'll continue to explore Buddypress features in greater detail.
