### ISSUE TITLE
Various Questions about BuddyPress Features

### ISSUE THREAD

**Issue by UncommonUnion** [UncommonUnion/WCV#21]
On the user profile “Forums” section it is not clear how to start a topic as there is no option to do so. 

How will “favoriting” items be represented on posts? It does not appear as anything on the user profile. A start like on Twitter, a like like on Facebook or other?

How will flagging posts/groups as inappropriate be monitored?

**Comment by UncommonUnion** [comment]
There were 2 forums (jobs and events) but we have been instructed to remove jobs in this recent feedback. To create a new event forum topic you must be logged in, go to NETWORK>EVENTS. On this page you can create a new event forum topic.

Favorited content appears in the user profile. If you favorite a post in a group, to can see that by going to your profile, clicking on "Activity" and the "Favorites" sub tab.

For inappropriate content there is a moderation plugin that allows user to flag inappropriate content; the settings for this button are controlled in the site admin. Right now it is set so that after a post is flagged as inappropriate 5 times, it is removed and the author is sent a warning message.

**Comment by lamminmaki** [comment]
OK!
