### ISSUE TITLE
Remaining Designs

### ISSUE THREAD

**Issue by UncommonUnion** [UncommonUnion/WCV#22]
Design – Please complete the design mock ups that have not been completed as well as the style guide and photo editing strategy

Key Page Design Mockups - UU (3-5 for CMP and below for WCMV)
Homepage
Resources
About page (standard page)
Open Network
Closed Network
Account Page
News and Events
Voices
Member Profiles
A form page (Ask an expert or become a member)
Style Guide 
Photo editing strategy

**Comment by UncommonUnion** [comment]
Sure. The decision was made to push the build, because the site is complex, to provide better functional guidance in the designs. The contract calls for 6-10 total designs, etc. so there was an understanding from the outset that designs would be budgeted toward the most important features.

**Comment by UncommonUnion** [comment]
Also regarding pages like "Advisory Services" which currently have nothing on them - the data entry is to be handled by Interpeace. Finally, many of these pages should work with the standard content template so this might not be the best thing to mock up (although this was mentioned as being an important page). i.e. there is a working site to apply feedback to, so mock ups are not always necessary.

As mentioned, we gone through a planning, design process, and completed production work on the network page. If this page needs more design work, we need more direction from your team.

**Comment by lamminmaki** [comment]
Hi Paul, I will close this and create separate items for the issues we want to raise.
