### ISSUE TITLE
CMP site

### ISSUE THREAD

**Issue by lamminmaki** [UncommonUnion/WCV#24]
The updated design of the CMP site (http://uncommonunion.com/client-work/wcv/design/revisions/index.php?page=cmp) looks good. 

The home page has a link to WCMV.org. It should be WCV.org. 

We can come back to this once the WCV site is in order.

**Comment by UncommonUnion** [comment]
implemented

**Comment by lamminmaki** [comment]
CMP site to be reviewed later.

**Comment by UncommonUnion** [comment]
Ok. You can provide just address tweaks then and follow the current direction.

**Comment by lamminmaki** [comment]
OK!
