### ISSUE TITLE
Design - News & Events 

### ISSUE THREAD

**Issue by lamminmaki** [UncommonUnion/WCV#25]
We'd like to have alternative mock-ups of the News & Events page (http://dev-constitution-making-for-peace.pantheonsite.io/category/news-events/) that are more engaging. For now news are rather small compared to events.

**Comment by UncommonUnion** [comment]
Added to client area.

**Comment by UncommonUnion** [comment]
http://uncommonunion.com/client-work/wcv/

**Comment by lamminmaki** [comment]
We feel that the layout to show "News" and "Events" in the same page does not work extremely well. We think it's best to combine the two into a single "News" page (I've already made the change to the top menu on (http://dev-constitution-making-for-peace.pantheonsite.io/). 

The "News" page layout can be based on the new mock-up, but could you 1) make the featured item - including the featured image - smaller, 2) remove the banner picture, 3) rename the page as "News", 4) show more news items in a single page, and 5) show the date when each item was published.

The page could take inspiration from http://www.interpeace.org/news-and-press/latest-news/ but with the latest news item or two being featured more prominently.

**Comment by UncommonUnion** [comment]
ok. done.

**Comment by lamminmaki** [comment]
We thank the effort but still feel this page does not fully meet our requirements in clarity and layout. As it currently is:
1. The pictures and posts take too much space. While the latest news item can be featured and be larger than other posts, a full screen of the "News" page (regardless of screen resolutions) should reveal more information. Please see below a comparison of full screenshots: 
2. Posts should be more clearly separated. 
3. Currently only posts tagged as "Events" appear on the page. This should be changed so that posts tagged with "News" appear here. 

I am happy to discuss this further over Skype if helpful. 

![news crisis group](https://cloud.githubusercontent.com/assets/19553399/18053389/6433fe32-6dff-11e6-9525-1298bbe4ba20.png)

![news interpeace](https://cloud.githubusercontent.com/assets/19553399/18053390/64444ce2-6dff-11e6-9268-accda168872f.png)

![news wcv](https://cloud.githubusercontent.com/assets/19553399/18053454/af76dcfc-6dff-11e6-808f-6d0592a843ad.png)

**Comment by lamminmaki** [comment]
Enable pagination or an alternative way to show more items. There should be a maximum no. of posts shown per page.

**Comment by lamminmaki** [comment]
Photo captions should not be visible on the "News" page - only when individual posts are accessed. 

![photo caption news](https://cloud.githubusercontent.com/assets/19553399/18053674/f2eb5caa-6e00-11e6-9cea-0fda8db12ba1.png)

**Comment by UncommonUnion** [comment]
Ok. A few points. The requirements for the news page have gone through an evolution. At one point we were told that the news should be searchable, news & events should be combined, etc.

The current category assignment was based on changes implemented by the Interpeace team. Based on feedback we've overridden some of your changes and restored the search for news.

Now, the news page only returns news, added search, made the style changes consistent with other search results which also seem to meet the requirements described above. I reduced the page size to 5 items so you can see the pagination. All the news search properties can be controlled here: https://dev-constitution-making-for-peace.pantheonsite.io/wp-admin/admin.php?page=uwpqsfform&uformid=817&uformaction=edit

**Comment by lamminmaki** [comment]
Thanks Paul - looks great. 

A final request: Can we remove "Related items" from the bottom of the page? 

![news related items](https://cloud.githubusercontent.com/assets/19553399/18119133/6a40f482-6f59-11e6-88eb-2ba41728e0ff.png)

**Comment by UncommonUnion** [comment]
removed

**Comment by lamminmaki** [comment]
OK!
