### ISSUE TITLE
Design - About

### ISSUE THREAD

**Issue by lamminmaki** [UncommonUnion/WCV#26]
We'd like to have alternative mock-ups of the About page (http://dev-constitution-making-for-peace.pantheonsite.io/womens-constitution-making-voices/about-wcv/) that are more engaging.

**Comment by UncommonUnion** [comment]
Added to client area:
http://uncommonunion.com/client-work/wcv/

**Comment by lamminmaki** [comment]
Thank you - the layout is quite similar to the original one. Please keep the page as is for the moment.
