### ISSUE TITLE
Voices

### ISSUE THREAD

**Issue by lamminmaki** [UncommonUnion/WCV#27]
Voices page should only show "Voices" - videos, stories etc. but not news and events.

**Comment by UncommonUnion** [comment]
This is just a matter of how you categorize posts. If posts are categorized only as news or events, they will only appear in that sections. I've changed categories accordingly in the demo content.

**Comment by lamminmaki** [comment]
This problem still persists. Two news item appears on the "Voices" page (http://dev-constitution-making-for-peace.pantheonsite.io/womens-constitution-making-voices/voices/). 

What are the categories that make items appear on the "Voices" page?

Can we set only one category - voices - for items that are meant to appear on the "Voices" page?

**Comment by lamminmaki** [comment]
And although it does not belong on that page, it is worth noting that the news item on Ottawa Peace Talks looks pretty weird on the "Voices" page (http://dev-constitution-making-for-peace.pantheonsite.io/womens-constitution-making-voices/voices/). It is showing the wrong featured image, smaller images etc.

**Comment by lamminmaki** [comment]
Posts marked as resource highlights also show up as "voices": http://dev-constitution-making-for-peace.pantheonsite.io/womens-constitution-making-voices/voices/.

**Comment by lamminmaki** [comment]
There appears to be a maximum number of posts that are shown on "Voices" page. Ten items are now shown while the latest video I've added - http://dev-constitution-making-for-peace.pantheonsite.io/nene-konate/ - does not appear on the page. What is the method to show more posts?

**Comment by UncommonUnion** [comment]
These issues have been fixed; some of this was addressed in a previous ticket. Make sure voices are designated as "voices" - pagination have been turn on for voices page - it got disabled during testing.

**Comment by lamminmaki** [comment]
OK!
