### ISSUE TITLE
Designs - Search, Account and Sign Up

### ISSUE THREAD

**Issue by lamminmaki** [UncommonUnion/WCV#28]
We'd like to see the Search button and Sign Up button in red color or redesigned in some alternative way.

**Comment by UncommonUnion** [comment]
The previous color matched the accent color, but it has been shifted to be redder.

**Comment by lamminmaki** [comment]
Sorry Paul - I was referring to the "Sign Up" button in the "Sign Up for Updates" Form at the bottom of a page. Similarly, I was referring to the "Search" button that comes up for example on the "Resources" and "Voices" page.
1. Can we make sure all buttons (including the ones on the "Network" page) are similar design - sharp edges and similar size and font
2. All buttons in same color - primarily accent color (WCV red) if it works

**Comment by UncommonUnion** [comment]
done.

**Comment by lamminmaki** [comment]
Looks great now - can we just make the "More" button on "Voices" page a bit smaller and thus consistent with the other buttons? 

![more button](https://cloud.githubusercontent.com/assets/19553399/17803873/536a0cf8-65f9-11e6-82fd-7f31a4f99c9e.png)

**Comment by UncommonUnion** [comment]
done.

**Comment by lamminmaki** [comment]
Perfect - thank you.
