### ISSUE TITLE
Sharing material in groups/profile

### ISSUE THREAD

**Issue by lamminmaki** [UncommonUnion/WCV#29]
- Uploading images to posts does not work - produces a "Failed" messsage (see attached image)
  ![upload a file](https://cloud.githubusercontent.com/assets/19553399/16303399/bce5c0b2-3950-11e6-8cf5-9dfa90168419.png)
  . Would be good to note if there are limitations (size etc.) to uploading images. 
- Sharing a video produces a duplicate post. 
- Sharing a link does not work. Nothing happens after you press "Add link". 
- Add documents button produces a browser message (see attached image). 

![add documents](https://cloud.githubusercontent.com/assets/19553399/16303210/d59da346-394f-11e6-9bd6-f2d0fbae51ce.png)

**Comment by UncommonUnion** [comment]
These are due to the development server configuration. We will see about moving to another server or chase this down. This is a configuration issue with the non-final server, but works on our local development machine - so this is non-critical but we will still, of course, resolve.

**Comment by UncommonUnion** [comment]
This is issue except for the image upload should be resolved... as mentioned, this is due to the server configuration. Looking at how to resolve in the dev environment now.

**Comment by lamminmaki** [comment]
The first three issues seem to be solved and everything appears to work normally. The ability to share documents has been removed. Is there any way to bring this back?

**Comment by UncommonUnion** [comment]
That should be working. Will look at that. Thanks for the headsup.
-p

Uncommon Union. Learn more > uncommonunion.com http://uncommonunion.com/
Paul Rene Johnson 

UNCOMMON UNION

Brooklyn | Ste 119, 231 Front St, Brooklyn New York 11201 

Mobile. 646.243.9859
Office. 929.276.3952
Conference. 646.448.9448
Website. uncommonunion.com http://uncommonunion.com/

**Comment by lamminmaki** [comment]
Thanks! Otherwise everything is starting to look good here. Mobile testing remaining the last outstanding item.

**Comment by UncommonUnion** [comment]
The document sharing is working. I just uploaded a test document in an update and it appeared under the documents tab. Note that document posting must happen within a group; this is a requirement of the document plugin-otherwise there is no context.
