### ISSUE TITLE
Access to back-end

### ISSUE THREAD

**Issue by lamminmaki** [UncommonUnion/WCV#30]
Hi Paul. Just wanted to ask you what you think would be the best timing for us to have access to the back-end of the site? Our comms team noted that they could already start tagging resources, voices, and making minor adjustments to content on some pages.

**Comment by UncommonUnion** [comment]
I sent credentials via email as opposed to a public forum. We can start entering content ASAP.

**Comment by lamminmaki** [comment]
OK!
