### ISSUE TITLE
New content

### ISSUE THREAD

**Issue by lamminmaki** [UncommonUnion/WCV#31]
There are a few items that could already be added to the site: 
- Michele Brandt's presentation at the Ottawa Peace Talks (http://peacetalks.net/talks/michele-brandt/) to the "Voices" section. We are working on a short description that will be added later on. 
- "Including women's voices in Constitution-Making" web story (http://www.interpeace.org/2015/11/including-womens-voices-in-constitution-making/) to be "News" section. 

Three other videos and several other items are currently being produced and we'll try to share them with you in the coming days. I'll include them in this post as they become available.

**Comment by UncommonUnion** [comment]
Thanks, we can provide access to the site and your team can begin populating final content when you are ready. The content we've provided is dummy / example content.

**Comment by lamminmaki** [comment]
OK!
