### ISSUE TITLE
Sidebar items: FILE NOT FOUND

### ISSUE THREAD

**Issue by lamminmaki** [UncommonUnion/WCV#32]
There appears to be a problem with file paths in sidebars. 

Clicking an item in a sidebar ends up in a "File not found" message. This problem happens on many pages, including "News" (http://dev-constitution-making-for-peace.pantheonsite.io/category/news-events/) and in individual posts (for example: http://dev-constitution-making-for-peace.pantheonsite.io/peace-through-diversity-and-inclusive-constitution-making/).

**Comment by UncommonUnion** [comment]
This was due to peculiarities of the dev server not rendering links correctly. This has been fixed.

**Comment by lamminmaki** [comment]
OK!
