### ISSUE TITLE
Banner picture

### ISSUE THREAD

**Issue by lamminmaki** [UncommonUnion/WCV#33]
We could not find a way to change or remove the banner picture page-specifically? How can this be done?

The banner picture quickly becomes repetitive and takes space so we intend to remove it from a number of pages. We might also want to change the banner picture in other pages.

**Comment by UncommonUnion** [comment]
There is a "WCMV Header" section on each page. Upload the image there. Make sure you select the "Slide" checkbox if you want it to replace the default slide show. You can add as many slides as you want. If you want nothing on top, just create an empty slide.

**Comment by lamminmaki** [comment]
Thank you clarifying that!

**Comment by lamminmaki** [comment]
The "Home" page banner shows small play and pause buttons. Is it possible to disable these if there is only one slide? 

![play button](https://cloud.githubusercontent.com/assets/19553399/17806278/d6f1e8b6-6603-11e6-96cf-f07a99ce159a.png)

**Comment by UncommonUnion** [comment]
removed.

**Comment by lamminmaki** [comment]
OK!
