### ISSUE TITLE
Remove "Ask an Expert" section

### ISSUE THREAD

**Issue by lamminmaki** [UncommonUnion/WCV#34]
"Ask an Expert" section should be removed from all pages. We already have the "Advisory services" form so this is not necessary. 

Problem visible at least here:
http://dev-constitution-making-for-peace.pantheonsite.io/peace-through-diversity-and-inclusive-constitution-making/
http://dev-constitution-making-for-peace.pantheonsite.io/michele-brandt-how-can-a-constitution-build-peace/

![ask an expert](https://cloud.githubusercontent.com/assets/19553399/17699217/cff62d06-63bf-11e6-968e-46790e84ed13.png)

**Comment by UncommonUnion** [comment]
removed.

**Comment by lamminmaki** [comment]
OK!
