### ISSUE TITLE
Photo captions

### ISSUE THREAD

**Issue by lamminmaki** [UncommonUnion/WCV#35]
Having experimented with posts and photos, we've encountered the following problems:
1. Photo captions on featured images are not shown in posts. This can be problematic as we have to credit photographers. 
2. Some pictures with photo captions do not respect the layout of the website.
3. Photo captions get mixed up with main text and are not distinctive enough. Please compare the attached picture with http://www.interpeace.org/2015/11/including-womens-voices-in-constitution-making/. 
   ![photo captions](https://cloud.githubusercontent.com/assets/19553399/17702853/edfc64a4-63cf-11e6-8803-e75880032c0c.png)

**Comment by UncommonUnion** [comment]
added / fixed.

**Comment by lamminmaki** [comment]
OK!
