### ISSUE TITLE
Background picture

### ISSUE THREAD

**Issue by lamminmaki** [UncommonUnion/WCV#36]
We could not find a way to change the background picture - how can we do that?

**Comment by UncommonUnion** [comment]
The background image is not content. It is a design element and finding images that can work as backgrounds and not make the site busy, cropping just so, etc. is non-trivial. It is possible to change the background image, of course, but this should be done by editing the theme. You can swap the image easily by replacing an image in the theme directory. This should be done by a web designer.

**Comment by lamminmaki** [comment]
Noted - thanks!
