### ISSUE TITLE
Related items on "Voices" page

### ISSUE THREAD

**Issue by lamminmaki** [UncommonUnion/WCV#37]
Having inserted more content, a "Related" section has appeared on the "Voices" page (http://dev-constitution-making-for-peace.pantheonsite.io/womens-constitution-making-voices/voices/). 

This section is not really necessary - we only need related items to be showed for individual posts. 

The template on the "Voices" page, however, appears cleaner than the one currently used for individual posts. Sometimes posts appear crowded (see for example: http://dev-constitution-making-for-peace.pantheonsite.io/including-womens-voices-in-constitution-making/) and the reader has to do quite a bit of scrolling to read the whole article. 

Would it be possible try the template from "Voices" page - where related items are shown at the bottom - as a default? 

![voices related](https://cloud.githubusercontent.com/assets/19553399/17729555/0e7aec6a-6465-11e6-8f3d-f3cbf4b6181f.png)

**Comment by UncommonUnion** [comment]
Ok. We cannot swap templates like that, but we built a new page for you and moved related items there. Note, that you need to categorize the post as "Voice" for the page to layout like this.

**Comment by lamminmaki** [comment]
Much appreciated Paul - but would it be possible to use other category than "Voice" for the template?  Perhaps "Spotlight". 

This would be so that we can use this template for other posts, such as news, but do not want them to appear in the "Voices" page. It would be good to be able to choose between the two templates (related items in the sidebar or at the bottom of the page) based on content.

Furthermore, can we see that the style, including underlining and font size, of "Related" (or if you can change it to "Related items" that would be even better) is similar to other section titles (see attached picture). 

![related items style](https://cloud.githubusercontent.com/assets/19553399/17803289/cfc207b4-65f5-11e6-946f-89588d8ce939.png)

**Comment by UncommonUnion** [comment]
Created a new category called "Spotlight" - the layout will be applied to posts with this category too. Made the requested style change as well.

**Comment by lamminmaki** [comment]
Perfect - thank you!
