### ISSUE TITLE
No. of featured resources on "Home" page

### ISSUE THREAD

**Issue by lamminmaki** [UncommonUnion/WCV#38]
We found a way to limit the number of news items shown on the home page (http://dev-constitution-making-for-peace.pantheonsite.io/). However, there does not appear to be a way to do the same for featured resources.

![featured resources item limit](https://cloud.githubusercontent.com/assets/19553399/17731398/5794ce72-646d-11e6-9c98-e5c3b86533ba.png)

**Comment by UncommonUnion** [comment]
Ok. This is now set up to render the same number of resources as news items, so both are controlled by the "numberposts" shortcode attribute.

**Comment by lamminmaki** [comment]
OK!
