### ISSUE TITLE
Publication dates

### ISSUE THREAD

**Issue by lamminmaki** [UncommonUnion/WCV#41]
Is it possible to show the publication dates of posts? I've attached an example below:

![publication date](https://cloud.githubusercontent.com/assets/19553399/17804642/e2de6200-65fc-11e6-9067-56f29064c0aa.png)

.
.
.

It would be preferable to see the publication dates on all pages - if possible. This would be particularly important for "News" items.

Finally, is it possible to change "News" to "Latest news" on front page? 

.
.
.

![publication date 2](https://cloud.githubusercontent.com/assets/19553399/17804720/2da6b1de-65fd-11e6-84c2-0d8241656339.png)
![publication date 3](https://cloud.githubusercontent.com/assets/19553399/17804719/2da63f56-65fd-11e6-817c-a982b271b3f7.png)

**Comment by UncommonUnion** [comment]
done

**Comment by lamminmaki** [comment]
There are still few instances where the publication date is not shown (see attached picture). For consistency it would be great if publication date is visible in all posts across the site. 

![publication date](https://cloud.githubusercontent.com/assets/19553399/18054404/f79c763c-6e03-11e6-849f-17f2549a7b80.png)

**Comment by UncommonUnion** [comment]
Wordpress doesn't like to show the same post date twice. Fixed. Added to all posts.

**Comment by lamminmaki** [comment]
OK - perfect!
