### ISSUE TITLE
Events and Jobs/Scholarships layout/style

### ISSUE THREAD

**Issue by lamminmaki** [UncommonUnion/WCV#42]
Is it possible to improve the look of the Events and Jobs/Scholarships pages? 

Events: http://dev-constitution-making-for-peace.pantheonsite.io/forums/forum/forum-events/
Jobs/Scholarships: http://dev-constitution-making-for-peace.pantheonsite.io/forums/forum/forum-jobs/

Now the pages look like this:
![jobs and scholarships](https://cloud.githubusercontent.com/assets/19553399/17805560/5647753a-6600-11e6-9a71-2da5f38b59cf.png)

It would be perfect if they could reflect the "Events" section on the "Network" page:

![events](https://cloud.githubusercontent.com/assets/19553399/17805496/13865bd0-6600-11e6-9405-f9375a12c060.png)

**Comment by UncommonUnion** [comment]
We cleaned up the layout. It is a little different than the index on the Network page for technical reasons, but it is now very much in tune with the site treatment.

**Comment by lamminmaki** [comment]
Looks cleaner indeed. Is it possible to remove a bit more of the clutter (see attached image)? This goes for both Events and Jobs/Scholarships. 

![events](https://cloud.githubusercontent.com/assets/19553399/18054822/bd963d72-6e05-11e6-856c-201f4db77868.png)

**Comment by UncommonUnion** [comment]
removed.

**Comment by lamminmaki** [comment]
OK!

**Comment by lamminmaki** [comment]
Just a quick clarification: Is there a way to show the text field for these forum pages? For now the text added in the editor does not appear on the page (see attached image). 

It would be great if the text can be shown between the page title and the subscribe option. This allows us to add a short description about the pages. 

![forums](https://cloud.githubusercontent.com/assets/19553399/18119415/c5e19eda-6f5a-11e6-99d1-bf0d9713d8e2.png)

**Comment by UncommonUnion** [comment]
add

**Comment by lamminmaki** [comment]
OK!
