### ISSUE TITLE
Posting updates from profile

### ISSUE THREAD

**Issue by lamminmaki** [UncommonUnion/WCV#43]
There appears to be a bug in the selection boxes when posting updates in the network profile. Words are crammed together and there are no spaces between words (see attached picture). 

![topics](https://cloud.githubusercontent.com/assets/19553399/17808747/13827670-6612-11e6-81df-dc48fcb9fa92.png)

**Comment by UncommonUnion** [comment]
fixed

**Comment by lamminmaki** [comment]
OK!
