### ISSUE TITLE
Problems with posting on Events and Jobs/Scholarships

### ISSUE THREAD

**Issue by lamminmaki** [UncommonUnion/WCV#44]
Copy-pasting information from other websites appears as code: 

![posting on events and jobs](https://cloud.githubusercontent.com/assets/19553399/17809075/62805db2-6614-11e6-945c-9c628bdfd215.png)

**Comment by UncommonUnion** [comment]
That is your computer's clipboard. It has nothing to do with wordpress or the site. Try pasting the text into a text document with no formatting first and then recopy it. That should remove formatting.

**Comment by lamminmaki** [comment]
OK!
