### ISSUE TITLE
Sign up for updates

### ISSUE THREAD

**Issue by lamminmaki** [UncommonUnion/WCV#45]
Signing up for updates results in an error message but perhaps there are still settings to be configured... 

![sign up for updates](https://cloud.githubusercontent.com/assets/19553399/17809246/856b056a-6615-11e6-9511-df5f53d4aab2.png)

**Comment by UncommonUnion** [comment]
Yes, it is necessary to specify an email list in the admin (this is in the mail chimp settings).Weleft this open because you have many lists. Sorry I did not mention this. We set it to:

WCV Events

**Comment by lamminmaki** [comment]
OK - noted!
