### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by UncommonUnion** [UncommonUnion/WCV#5]
Does not work extremely well. For instance, the keyword “handbook” does not produce a copy of the constitution-making handbook but different parts, chapters or subchapters of the handbook. Links to these do not work.

**Comment by UncommonUnion** [comment]
I added an additional plugin for general searching ("Better Search") for more administrative control. The resource searching is handled by the Ultimate WP Query Search Filter plugin which allows for complex queries. 

Finally, and probably most significantly, I've exposed tags for all post types. This means you can tag posts with appropriate keywords which will help you refine results.

**Comment by lamminmaki** [comment]
Thank you. We will test the search function to a greater extent once more resources have been listed.

**Comment by lamminmaki** [comment]
I'll keep this open for now, until we've done a bit more testing.

**Comment by lamminmaki** [comment]
Search on "Resources" page brings good results and seems to be working well.

The other "Search" button, next to account login, however, seems to work differently as it produces different results. The results are also presented in a single post format, which is not so clear. Can we use the search function on "Resources" page as the standard (search results, results page etc.). 

![searching the site](https://cloud.githubusercontent.com/assets/19553399/17731767/17458e36-646f-11e6-88ba-e78fc3b04baf.png)

**Comment by UncommonUnion** [comment]
done

**Comment by lamminmaki** [comment]
Something doesn't quite match yet - look at the search results for "handbook" in both searches. The Resources search seems perfect, while the site search shows handbooks as related items. 

![resources search](https://cloud.githubusercontent.com/assets/19553399/18056993/7d97f888-6e0e-11e6-8828-783c419b101f.png)
![site search](https://cloud.githubusercontent.com/assets/19553399/18056992/7d91a74e-6e0e-11e6-9be9-b700725be805.png)

**Comment by lamminmaki** [comment]
Thinking of it, the "Related items" sidebar can be removed from the search result page.

**Comment by UncommonUnion** [comment]
Removed related items. The general search is not a resource search, so all content which mentions "handbook" in the query is returned. If you flip through the pages, you will see all the other content in there. The resource search is controlled here: https://dev-constitution-making-for-peace.pantheonsite.io/wp-admin/admin.php?page=uwpqsfform&uformid=734&uformaction=edit

The general search is a default Wordpress function.

**Comment by lamminmaki** [comment]
OK - noted!
