### ISSUE TITLE
Mail chimp

### ISSUE THREAD

**Issue by UncommonUnion** [UncommonUnion/WCV#6]
Where does this link up to? The form does not work – will this be the Interpeace mailchimp account?
The Mailchimp list unique id is 9785134d85.

**Comment by UncommonUnion** [comment]
All set for Mail Chimp. I need more than the list id. Can you provide an API Key for this account and / or email me you login credentials?

**Comment by lamminmaki** [comment]
API Key is 887afc350f2cb426b0579ff66436da1a-us11. Let us know if you need anything else.

**Comment by UncommonUnion** [comment]
ok. Added! That should be all you need.

**Comment by lamminmaki** [comment]
OK!

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @lamminmaki)
