### ISSUE TITLE
Remove Jobs Forum

### ISSUE THREAD

**Issue by UncommonUnion** [UncommonUnion/WCV#7]
Remove events and jobs/scholarships from the page and “Network” drop down menu.

**Comment by lamminmaki** [comment]
How can we edit content, including the introductory text, on the "Network" page (http://dev-constitution-making-for-peace.pantheonsite.io/womens-constitution-making-voices/network/) and what is the procedure to change the order of the sections if necessary? 

For instance, what is the procedure to re-introduce the Jobs forum to the "Network" page at a later stage? We notice from the back-end it is only possible to bring it back to the Top menu (see here: http://dev-constitution-making-for-peace.pantheonsite.io/).

**Comment by UncommonUnion** [comment]
The network page is programmatic and brings together many dynamic features. It is not possible to edit as a content page. If you want to make changes to this page it will be necessary to alter the theme.

**Comment by lamminmaki** [comment]
OK!

**Comment by lamminmaki** [comment]
Paul - given that we are not able to edit the contents of the "Network" page, could we re-introduce the Jobs/Scholarships section? I know we asked this to be removed before but given the limited options of putting this back at a later stage we would prefer to have it visible. Sorry for the extra trouble - hope this can still be implemented.

**Comment by UncommonUnion** [comment]
I had a feeling you'd might change your mind, so I kept the markup. Restored...

...also you need to clean up your forum text and strip the HTML from your copy / paste.  BTW, there are many tools to strip HTML throughout the web if you are going to copy / paste HTML content. .i.e.: http://www.striphtml.com

**Comment by lamminmaki** [comment]
OK - thank you!
