### ISSUE TITLE
Markup Instructions

### ISSUE THREAD

**Issue by UncommonUnion** [UncommonUnion/WCV#8]
There is HTML on the “Featured resources” once you click them. 

XHTML: You can use these tags: <a href="" title=""> <abbr title=""> <acronym title=""> <b> <blockquote cite=""> <cite> <code> <del datetime=""> <em> <i> <q cite=""> <s> <strike> <strong>

**Comment by UncommonUnion** [comment]
Removed.

**Comment by UncommonUnion** [comment]
While the “Featured Resources” on “Resources” page (http://dev-constitution-making-for-peace.pantheon.io/womens-constitution-making-voices/voices/) are not supposed to be posts from the “Voices” section (see above comment), once you click these posts they have HTML on them under the comment section (http://dev-constitution-making-for-peace.pantheon.io/irreversible-womens-full-participation-in-constitution-making-processes/). The same happens once you access these posts through the “Voices” section.

**Comment by UncommonUnion** [comment]
Fixed. Highlighted resources can be selected via the back end.

**Comment by lamminmaki** [comment]
OK!
